<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-18T15:25:01 IST" name="Default suite" finished-at="2024-02-18T15:26:20 IST" duration-ms="78614">
    <groups>
    </groups>
    <test started-at="2024-02-18T15:25:01 IST" name="Default test" finished-at="2024-02-18T15:26:20 IST" duration-ms="78614">
      <class name="epack.DemoTest">
        <test-method is-config="true" signature="configuration()[pri:0, instance:epack.DemoTest@64cd705f]" started-at="2024-02-18T15:25:03 IST" name="configuration" finished-at="2024-02-18T15:25:11 IST" duration-ms="7666" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configuration -->
        <test-method signature="testOne()[pri:0, instance:epack.DemoTest@64cd705f]" started-at="2024-02-18T15:25:11 IST" name="testOne" finished-at="2024-02-18T15:26:13 IST" duration-ms="62460" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PracticeAutomationHereaaa] but found [PracticeAutomationHere]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PracticeAutomationHereaaa] but found [PracticeAutomationHere]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at epack.DemoTest.testOne(DemoTest.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOne -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:epack.DemoTest@64cd705f]" started-at="2024-02-18T15:26:13 IST" name="tearDown" finished-at="2024-02-18T15:26:20 IST" duration-ms="6574" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- epack.DemoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
